name: Build and Release June App

on:
  push:
    branches:
      - feature/setup-release-configuration

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install Wine
        run: sudo apt-get update && sudo apt-get install -y wine64

      - name: Install dependencies
        run: npm install

      - name: Run release script
        run: npm run release

      - name: Print dist folder tree
        run: tree dist -L 2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/JuneDevGPT_WIN_*/JuneDevGPT_WIN_*.exe
          asset_name: ${{ github.event.repository.name }}.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset macOS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/JuneDevGPT_MACOS_*/JuneDevGPT_MACOS_*.app
          asset_name: ${{ github.event.repository.name }}.app
          asset_content_type: application/octet-stream
